version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    command: -p 5433

  server:
    build: server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/postgres

    ports:
      - '8081'
    depends_on:
      - postgres

  gateway:
    build: gateway
    environment:
      MY_SHARE_IT_SERVER_URL: http://server:8081

    ports:
      - '8080:8080'
    depends_on:
      - server
