version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    command: -p 5433

  server:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/postgres

    ports:
      - '8080:8080'
    depends_on: 
      - postgres 
